In [4]:
import numpy as np

In [8]:
X = np.array([1,2,3])
print(X)

[1 2 3]


In [9]:
B = np.array([10])
print(B)

[10]


In [10]:
print(X+B)

[11 12 13]


In [6]:
print(np.array([1,2,3]) + np.array([10,10,10]))

[11 12 13]
